# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py27


before_install:
  - sudo apt-get install swig
  - sudo apt-get install python-pygame
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install gfortran

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: tpbarron
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: tpbarron/rlcore
    condition: $TOXENV == py27
