# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

env:
  - TOXENV=py35
  - TOXENV=py27


before_install:
  - sudo apt-get install swig
  - sudo apt-get install python-pygame
  - sudo apt-get install libblas-dev liblapack-dev
  - sudo apt-get install gfortran

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox

# command to run tests, e.g. python setup.py test
script: python setup.py test
